# Generated by Django 5.2.6 on 2025-10-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_cambio_en_grado_y_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='editoriales/'),
        ),
    ]
