# Generated by Django 5.2.6 on 2025-10-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_editorial_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto', models.CharField(choices=[('Libro no encontrado', 'Libro no encontrado'), ('Docente interesado', 'Docente interesado'), ('Otro', 'Otro')], default='Libro no encontrado', max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('colegio', models.CharField(blank=True, max_length=255, null=True)),
                ('libro_solicitado', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contactos',
                'db_table': 'contactos',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
